### ISSUE TITLE
tikzLaTeXPackages not used with standAlone-option

### ISSUE THREAD

**Issue by minintaequ** [yihui/tikzDevice#100]
I tried to produce a standAlone tikz-Plot with an additional package as in the following example:

```r
options(tikzMetricPackages=c(getOption("tikzMetricPackages"), "\\usepackage{siunits}\n"))
options(tikzLaTeXPackages="\\usepackage{siunits}\n")
tikz("Plot.tex", standAlone=TRUE)
plot(1:3, xlab="height in \\centi\\metre")
dev.off()
```

tikz generates the file, but the preambel is only:

```latex
% Created by tikzDevice version 0.8.1 on 2015-01-23 16:41:58
% !TEX encoding = UTF-8 Unicode
\documentclass[10pt]{article}
\usepackage{tikz}

\usepackage[active,tightpage,psfixbb]{preview}

\PreviewEnvironment{pgfpicture}

\setlength\PreviewBorder{0pt}
\begin{document}
```

Shouldn't be there the additional package siunits from tikzLaTeXPackages? What am I doing wrong?

**Comment by krlmlr** [comment]
Sorry for my slow reply. I can only guess: Options are case-sensitive in R, have you tried `options(tikzLatexPackages=...)`?
