### ISSUE TITLE
Mac Os (Pumpkin Helmet) TikzDevice Crash. 

### ISSUE THREAD

**Issue by manu93** [yihui/tikzDevice#101]
Here is my problem:

I try to type `tikz("example")` and here is the message I get from R

```
*** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
1: .External(TikZ_StartDevice, file, width, height, onefile, bg,
  fg, baseSize, lwdUnit, standAlone, bareBones, documentDeclaration, 
  packages, footer, console, sanitize, engine, symbolicColors,
  colorFileName, maxSymbolicColors, timestamp)
2: tikz("example")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

If someone finds a way to solve it, please contact me!

**Comment by krlmlr** [comment]
I can replicate this on my Linux box. Does `tikz("example.tex")` work for you?

**Comment by manu93** [comment]
Oh yes, it works, what a nice result! I really didn’t understand that I had to write the extension: I was somehow convinced that the command would have activated a LaTeX-like quartz, not a LaTeX code (much better of course). 

Thank you very much for the help.

All the best,
Emanuele Belli
:
