### ISSUE TITLE
Error in file(texLog,"r") : cannot open the connection

### ISSUE THREAD

**Issue by duncjb** [yihui/tikzDevice#105]
Windows 7 SP1, R 3.1.2, knitr 1.9, tikzDevice 0.8.1. Session info:

> R version 3.1.2 (2014-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     

> loaded via a namespace (and not attached):
> [1] evaluate_0.5.5 formatR_1.0    knitr_1.9      stringr_0.6.2  tools_3.1.2   

If I run any .Rnw file using a tikz device anywhere, it comes up with this issue. The output from any file, no matter how basic (e.g. just setting the device to tikz and issuing a base graphics scatter of random data). This is the output:

> Loading required package: knitr
>
> processing file: filename.Rnw
>   |.............                                                    |  20%
>   ordinary text without R code
> 
>   |..........................                                       |  40%
> label: setup
>   |.......................................                          |  60%
>   ordinary text without R code
> 
>   |....................................................             |  80%
> label: plot (with options) 
> List of 2
>  $ fig.height: num 4
>  $ fig.width : num 4
> 
> Using TikZ metrics dictionary at:
> 	filename-tikzDictionary
> Quitting from lines 20-22 (filename.Rnw) 
> Error in file(texLog, "r") : cannot open the connection
> Calls: knit ... replayPlot -> <Anonymous> -> getMetricsFromLatex -> file
> In addition: Warning message:
> In file(texLog, "r") :
>   cannot open file 'C:/[path]/Local/Temp/Rtmp6B8kmS/tikzStringWidthCalc.log': No such file or directory

> Execution halted

If I use a PDF device, it works fine, but obviously without the tikz features. I've been using Tikz before without any problems, but it now seems to hit this block; I've also tried using different TeX engines, but it has no effect. I've tried rolling back the knitr and tikzDevice installation versions, but this didn't work either.

**Comment by krlmlr** [comment]
Thanks for reporting this. Could you please post such a "minimal" `.Rnw` file?

**Comment by duncjb** [comment]
Here you go:

>\documentclass{article}
>
>\begin{document}
>
><<plot, fig.height=4,fig.width=4,dev='tikz'>>=
>data <- data.frame(x=rnorm(100),y=rnorm(100))
>plot(data)
>@
>
>\end{document}

And that gets me the same message as above:

> Quitting from lines 6-8 (test1642200215.Rnw) 
> Error in file(texLog, "r") : cannot open the connection
> Calls: knit ... replayPlot -> <Anonymous> -> getMetricsFromLatex -> file
> In addition: Warning message:
> In file(texLog, "r") :
> cannot open file 'C:/[path]/AppData/Local/Temp/Rtmpwv5isn/tikzStringWidthCalc.log':  No such file or directory
> 
> Execution halted

**Comment by krlmlr** [comment]
@yihui: Do you have access to a Windows machine with an installation of LaTeX?

**Comment by yihui** [comment]
@krlmlr I do, but I cannot reproduce this issue.

**Comment by krlmlr** [comment]
@duncjb: How does your call to `knitr::knit` look like? Does the `[path]` part of the path in the error message contain any unusual characters, such as whitespace? Could you try knitting the following document:

```
\documentclass{article}

\begin{document}

<<temp>>=
tempdir()
tempfile()
dir(tempdir())
@

\end{document}
```

Where does your LaTeX installation reside? Is `tikzDevice` aware of it? Does the following `.R` script work for you:

```
library(tikzDevice)
tikz("filename.tex", width=4, height=4)
data <- data.frame(x=rnorm(100),y=rnorm(100))
plot(data)
dev.off()
```

(Those are all just wild guesses in the hope to find the cause for your problem. Thanks for your help.)

**Comment by duncjb** [comment]
Your wild guesses proved spot on: the temp folder path had a white space in it and that was causing the problems. I changed the temp directory location, and it works now. Not entirely clear why it used to work but then stopped, but this seems to have fixed it.

Thank you so much for your help - very much appreciated.

**Comment by krlmlr** [comment]
Thanks for your feedback. This issue is a dupe of #99 then.
