### ISSUE TITLE
Bug tikzDevice in R

### ISSUE THREAD

**Issue by manu93** [yihui/tikzDevice#115]
Hello,

I have just downloaded the new R version:
R version 3.2.0 (2015-04-16)

I downloaded the last version of filehash.r package and tikzDevice.r, but when I typed:
library(tikzDevice)

R gave me the following message:
-----------------------------------------------------------------------------
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/tikzDevice/libs/tikzDevice.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/tikzDevice/libs/tikzDevice.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.1/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/tikzDevice/libs/tikzDevice.so
  Reason: image not found
Errore: package or namespace load failed for ‘tikzDevice’
-----------------------------------------------------------------------------

Then I tried installing both again and got another message:

-----------------------------------------------------------------------------
Error in get0(hookname, envir = env, inherits = FALSE) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/tikzDevice/R/tikzDevice.rdb' is corrupt
Inoltre: Warning message:
In get0(hookname, envir = env, inherits = FALSE) :
  internal error -3 in R_decompress1
Errore: package or namespace load failed for ‘tikzDevice’
-----------------------------------------------------------------------------

I have never had problems using tikzDevice, the problem started right after the update to "Full of Ingredients"

Thank you very much for the help, bye!

**Comment by krlmlr** [comment]
I don't have a Mac, but it looks like you need to rebuild the package. Please run in a fresh R session (perhaps from the terminal):

```
install.packages("tikzDevice")
```

Everything should work afterwards.
