### ISSUE TITLE
Error with fontspec and option no-math

### ISSUE THREAD

**Issue by tpellard** [yihui/tikzDevice#119]
Trying to load the LaTeX package` fontspec` with the option `no-math` in an .Rnw file that uses tikzDevice produces an error `Error in getMetricsFromLatex(TeXMetrics)`. The same error also occurs when the package `mathspec` is loaded.

Here is a minimal example:
```LaTex
\documentclass{minimal}
\usepackage[no-math]{fontspec}
\begin{document}
```
```R
<<include=FALSE>>=
options(tikzDefaultEngine='xetex')
@ 
<<echo=FALSE, dev="tikz">>=
plot(1:100)
@
```
```LaTex
\end{document}
```
Commenting out either the `no-math` option in the package declaration or `dev="tikz"` resolves the problem.

This is the same issue as described here by someone else: http://stackoverflow.com/q/29023304/405151

This is a real issue since loading `fontspec` with the `no-math` option is the only way in XeLaTeX to harmonize the math font with the main text font.

**Comment by krlmlr** [comment]
Thanks for reporting this issue. It works for me with the following equivalent preamble:

```
\documentclass{minimal}
\PassOptionsToPackage{no-math}{fontspec}
\usepackage{fontspec}
```

This is related to #107.
