### ISSUE TITLE
\tikzexternalize and getMetricsFromLatex

### ISSUE THREAD

**Issue by gdkrmr** [yihui/tikzDevice#120]
```latex
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize

\begin{document}
<<dev="tikz">>=
library(ggplot2)
qplot(1)
@

\end{document}
```

Gives an error in ```getMetricsFromLatex```, if you add ```\tikzexternaldisable``` at the end of the preamble it works fine, maybe this should be made standard behaviour

**Comment by krlmlr** [comment]
Does it work for you if you move `\tikzexternalize` after `\begin{document}`? I barely remember the semantics of that command, but my test shows no extra error messages, and compilation succeeds.

Also, I can only guess that `knitr` attempts to construct a suitable preamble for `tikzDevice` and uses everything before `\begin{document}` in the `.Rnw` file. @yihui: Could you please comment?

**Comment by yihui** [comment]
I wonder why you need `\usetikzlibrary{external}` and `\tikzexternalize` at all, because **knitr** will pre-compile tikz graphics to PDF by default, which is more or less equivalent to `\tikzexternalize`.

**Comment by gdkrmr** [comment]
@krlmlr: moving ```\tikzexternalize``` after ```\begin{document}``` in the above example works fine.
@yihui: it is useful for if you want to use both tikz graphics and R code in a document, knitr will only externalize stuff inside ```<<>>= ... @```

The following code complains about not having enabled ```-shell-escape``` even though I did enabled the option in r-studio and works just fine without ```\tikzexternalize``` and works just fine if I put ```\tikzexternalize``` in the preamble:

```
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage{tikz}
\usetikzlibrary{external}


\begin{document}
\tikzexternalize
test

\tikz{
\node[draw]() {};
}

\end{document}
```

**Comment by gdkrmr** [comment]
From the pgf manual:

\tikzexternalize[ optional arguments ]
This command activates the externalization. It installs commands to replace every TikZ-picture. It
needs to be called before \begin{document} because it may need to install its separate shipout routine.

**Comment by krlmlr** [comment]
How about the following preamble:

```
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage{tikz}

%\begin{document}

\usetikzlibrary{external}
\tikzexternalize

\begin{document}
```

Everything up to the commented `\begin{document}` should be used for the tikzDevice preamble, which seems to be what is desired here.

**Comment by gdkrmr** [comment]
Let me tell you how I encountered the problem:

I have quite a large document (latex, not knitr) with a lot of figures that are made using the tikz device. To speed up compiling time at some point I put the external library in the preamble.

I have the preamble in a separate file (preamble.tex) and for the tikzdevice I declare the following options in all my R scripts that produce the figures:
```R
options(
  tikzDefaultEngine       = "pdftex",
  tikzDocumentDeclaration = readLines("../report.tex", n = 1, encoding = "UTF-8"),
  tikzLatexPackages       = "\\input{../preamble.tex}"
)
```
as soon as I included the tikz externalize library in the preamble everything broke with the ```getMetricsFromLatex``` error. I could fix it changing ```"\\input{../preamble.tex}"``` to   ```c("\\input{../preamble.tex}",  "\\tikzexternaldisable") ```

**Comment by krlmlr** [comment]
If I'm not mistaken, you could as well have excluded the `\tikzexternalize` command from `preamble.tex` and use it only in the "main" document. I think this is a sufficiently rare corner case that would be difficult to solve in tikzDevice or knitr, and where workarounds seem to exist. Therefore, I'm not at all sure if tikzDevice or knitr should do anything about it. Perhaps we could add a "known shortcomings" section in the vignette?

**Comment by gdkrmr** [comment]
\tikzexternalize must come before \begin{document}, else Latex aborts 
with an error. This is also what the pgf manual says.

**Comment by krlmlr** [comment]
Right. Have you tried the preamble I suggested before? https://github.com/yihui/tikzDevice/issues/120#issuecomment-139752645

**Comment by gdkrmr** [comment]
that one works, \tikzexternalize comes before \begin{document}

**Comment by krlmlr** [comment]
Does it work with knitr, too?

**Comment by gdkrmr** [comment]
it fails and latex complains that \tikzexternalize has to go into the 
preamble

**Comment by yihui** [comment]
How about this as the first code chunk of your Rnw document?

```r
<<include=FALSE>>=
assign('tikzPackages', '', envir = knitr:::.knitEnv)
@
```

**Comment by gdkrmr** [comment]
```latex
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize

<<include=FALSE>>=
assign('tikzPackages', '', envir = knitr:::.knitEnv)
@

\begin{document}
<<dev="tikz">>=
library(ggplot2)
qplot(1)
@

\end{document}
```
works :-), the first chunk can also go behind ```\begin{document}```

**Comment by krlmlr** [comment]
Thanks, @yihui and @gdkrmr. I guess this can be closed.
