### ISSUE TITLE
No transparency with raster grobs, e.g. ggplot2::geom_raster

### ISSUE THREAD

**Issue by bleutner** [yihui/tikzDevice#121]
Hi,

ggplot2 plots containing a `geom_raster`, or any other rasterGrob are saved by `tikz()` as png files without transparency. 

     tikz("test.tex", standAlone = TRUE) 
     ggplot() +  
        geom_point(aes(x = 2, y = 3))+        
        geom_raster(aes(x = 1:5, y = 1:5, fill = c(1:4, NA)), alpha = .5)+
        scale_fill_gradient(na.value = NA)
     dev.off()
     system("pdflatex --interaction=nonstopmode test.tex")

The png  test_ras1.png doesn't have transparency supplied via the alpha argument nor full transparency for NA cells (na.value argument). Instead fully transparent cells are "white" and semi transparent ones are opaque.

Best regards,
Benjamin

A screenshot from the pdf:
![selection_050](https://cloud.githubusercontent.com/assets/1650314/9472214/2c040544-4b54-11e5-8702-d5d51203e9bf.png)

**Comment by krlmlr** [comment]
Thanks for the bug report. I can replicate the issue on Ubuntu.

Changing `png_type` to `'cairo'` and using `bg = 'transparent'` in the call to `png` in the [code](https://github.com/yihui/tikzDevice/blob/f539a1b07450c7697d1e59e3af1c11d7b5b6f6b5/R/tikzInternal.R#L19-L79) resolves the issue for me, but I'm not at all sure about Windows and OS X. @yihui: Do you have access to a Mac and/or to a Windows machine?

**Comment by yihui** [comment]
Your fix looks good to me, as long as you figure out the Travis failure.

**Comment by krlmlr** [comment]
Yes, of course -- tests that use raster images are rendered differently now. I'll take a look at Windows and OS X in due time, too.

@bleutner: Which OS are you on? Does the fix work for you? Please install with `devtools::install_github("yihui/tikzDevice#122")`.

**Comment by bleutner** [comment]
The fix works perfectly.

I am also on Ubuntu (14.04 and 15.04, the fix works for both)). I don't have  a Windows or OSX machine, sorry.

**Comment by smason** [comment]
works for me under OS X (10.11)

**Comment by krlmlr** [comment]
@smason: Thanks for your feedback. Does it work without the patch, too?

**Comment by smason** [comment]
huh, didn't think of looking at the internal handling…  Yes, both before and after works fine but this patch shouldn't touch the OS X code path.

**Comment by krlmlr** [comment]
@smason: Well, the code path is different only if `capabilities("aqua")`. According to the R docs, this is true

> ... Only on some OS X builds, including CRAN binary distributions of R

What does `capabilities("cairo")` return on your system? Do you have a chance to test the other code path?

**Comment by smason** [comment]
I personally install R with `homebrew`, and it's true there as well.
I can't see an easy way of overriding capabilities, so I hacked the code to force the other code path (and checked with a `print`).  Everything seems OK there now as well, but has lots of white without the patch.

**Comment by krlmlr** [comment]
@smason: Thanks a lot for double-checking.

@yihui: If cairo can be expected to be available on all three major platforms nowadays (stll have to check on Windows), do you see a reason for maintaining the OS X "quartz" code path?

The help for options("bitmapType") reads:

> (Unix-only) character. The default type for the bitmap devices such as png. Defaults to "cairo" on systems where that is available, or to "quartz" on OS X where that is available.

It appears that [the check for this option](https://github.com/yihui/tikzDevice/blob/f81e4b85fc36deef2100f60d94d763fefdfa2b59/R/tikzInternal.R#L47-L48) is broken anyway, because this option is only queried on Windows.

**Comment by smason** [comment]
Personally, I'd default to cairo, and fall back to platform specifics only if/when needed.
I've always ensured my builds have cairo enabled as it has had the best support for features I cared about (mostly transparency and fonts), but other people may build differently…

**Comment by krlmlr** [comment]
On my Windows machine with R 3.2.0, `capabilities("cairo")` is true. (It wasn't for R 2.12.) I searched the R news for cairo, but haven't found any hint since when this is the case. And there's also the [Cairo package](https://cran.r-project.org/web/packages/Cairo/index.html), which also works for me on Windows -- now I'm totally confused :-o

**Comment by yihui** [comment]
@krlmlr I don't fully understand why the original authors choose quartz() on OS X. I know in a few cases antialiasing does not work well for `png(type = 'cairo')`, e.g. http://r.789695.n4.nabble.com/png-type-cairo-point-symbols-without-boarders-are-not-anti-aliased-td4678745.html Anyway, personally I'm not too worried about `capabilities('cairo')` (should be TRUE for most R users now). If R 2.x is a problem, I'd just drop 2.x support. It is not worth the consideration any more. I have dropped it in all the rest of my packages, and CRAN does not care about it, either.

**Comment by krlmlr** [comment]
@yihui: We definitely should drop R 2.x support in the upcoming release. Thanks for the information on cairo. What I still don't understand: Can we expect CairoPNG to work if `capabilities("cairo")` is `TRUE`?

**Comment by yihui** [comment]
CairoPNG is from the R package Cairo, which does not require `capabilities('cairo')` to be TRUE. It will always work as long as you can install it (which requires cairo as a system dependency on *nix when installing the package).

**Comment by bridgeovertroubledhuman** [comment]
Is there a way to use "scale_fill_gradient" **without** it creating a png at all? Because I'd rather have absolutely everything in TIKZ. Thanks

**Comment by rstub** [comment]
@bridgeovertroubledhuman Could you create a new issue referencing this? Thanks!

**Comment by bridgeovertroubledhuman** [comment]
Will take a while, as something else bugs me a lot atm and I am also not 100% sure, as it might be just me not knowing, if I use the ggplot right. So I'll first try a bit more, maybe it works, maybe it doesn't. Thanks!
