### ISSUE TITLE
Create tikz figures forcing labels featuring LaTeX's font size modifier-commands

### ISSUE THREAD

**Issue by T0J0** [yihui/tikzDevice#123]
Hi there,

according to my understanding of tikzDevice there is currently no option to force font size modifier-commands such as `\footnotesize` for text in plots. However, I think it would be a nice feature. E.g., in the [`xtable` package](https://cran.r-project.org/web/packages/xtable/) it can be specified. I am aware of the possibility to scale text in figures via the `pointsize` argument and build in R functions. But for consistency in any LaTeX document it would be great to work with the font size modifier-commands. Doing so, one may define a custom font size for figure labels in the preamble. Changes can then be applied consistently and without the need to re-create tikz-files with tikzDevice.

**Comment by krlmlr** [comment]
I'm not sure that changing the global font size modifier will be possible without re-creating the tikz-files. Part of this process is actually measuring text dimensions, which depend on the font size.

Also, I think this might actually work already if you add something like `\AtBeginDocument{\footnotesize}` to the LaTeX preamble.
