### ISSUE TITLE
Travis builds currently broken

### ISSUE THREAD

**Issue by krlmlr** [yihui/tikzDevice#125]
Last stable: https://travis-ci.org/yihui/tikzDevice/builds/79973427

First failing: https://travis-ci.org/yihui/tikzDevice/builds/80088477

Difference: https://github.com/yihui/tikzDevice/compare/181b4b84d4b0...7196eee0fef0

Reverting this patch didn't help: https://travis-ci.org/yihui/tikzDevice/builds/80091627

I really hope this is some infrastructure glitch that goes away by itself. I don't really have time to investigate this now.

**Comment by yihui** [comment]
Does it fail locally as well?

**Comment by krlmlr** [comment]
Local tests work (well, actually, fail, but fail differently). On Travis, it's

```
! LaTeX Error: File `tikz.sty' not found.
```

https://travis-ci.org/yihui/tikzDevice/jobs/80091630#L2104

**Comment by krlmlr** [comment]
Just restarted the last successful build on master: https://travis-ci.org/yihui/tikzDevice/builds/79973427 . It's a pity that Travis doesn't assign new build numbers in this case, so the "last stable" might not be stable anymore.

**Comment by krlmlr** [comment]
No infrastructure glitch, just two different failure reasons. Part of the problem fixed in da61209f7fad5860, an alternative implementation for #112 will fix the rest.

@yihui: Are you still registered with AppVeyor? https://ci.appveyor.com/project/yihui/tikzDevice shows "access denied".

**Comment by yihui** [comment]
I don't know why my account was lost. I just registered again.
