### ISSUE TITLE
[FR] Use tikzDevice with only tikzMetricsDictionary

### ISSUE THREAD

**Issue by pank** [yihui/tikzDevice#126]
Hi,

###### Background
I want to produce a report on an external production machine with data I cannot copy off of the machine.  It's preferable not to install additional software, and when the machine was set up, TL wasn't installed.
`tikz` is the optimal format for graphics here since it can be inlined (only one file to copy) and since it's pretty.

###### Premises or my understanding 
My understanding is that the LaTeX compiler is only needed for finding the width of characters.  For the graph I produce, I know the set to characters that can come up.  I know the font.  I know the size.
I would like to solely rely on `tikzMetricsDictionary`, which I can pre-compute on my local machine.

###### Problem
However, when I try to load `tikzDevice` it fails since it doesn't find the LaTeX compiler.

###### Question
1. would it even be possible to typeset a graph without latex assuming all metrics are available in `tikzMetricsDictionary`? 
2. if so, would it be possible to add an option that tells `tikzDevice` to not check for the availability of LaTeX?

[I searched online beforehand, but nothing came up].

Thanks,
Rasmus

**Comment by krlmlr** [comment]
1. Creating the TeX code is certainly possible without LaTeX. As you guessed, LaTeX is needed only for measurement.
2. I tried something along those lines in #112 but reverted in favor of simplicity. Your case certainly makes sense, I'll think about it.

If you would be willing to supply a pull request, I'd be happy to review it. I think the check that currently happens in `.onLoad` should happen upon the first invocation of any of the string measurement functions.  Some care is needed because that code sets global options.

**Comment by krlmlr** [comment]
NB.: Try the current GitHub version: `devtools::install_github("yihui/tikzDevice")`. I think this might already work, there will be a warning (instead of an error) when the package is loaded, but measurement should resort to the cached values.

**Comment by pank** [comment]
Hi,

Cool. In that case there are really two things needed for this IMO. First and most importantly the fix you suggest. This is really a 'bugfix' and need not be documented. Second, and perhaps optionally, a user level function to generate tikzMetricsDictionary, plus documentation probably even in the vignette. A priori this function seems to simply be a map around a list of strings (change the terms to the proper R terms as necessary).

I can allocate time towards this, but I may need help as I'm only familiar with tikzDevice as a user. For starters, is it correct that the width is always calculated for a single character and not for full strings? It seems to be the case in my example but I don't know if it's a general property.

Thanks,
Rasmus

**Comment by pank** [comment]
Cool; That was easy!

I'll try to use the dev version. I say /try/ since I don't have a build env. for windows (as I recall there's a src dir in tikzDevice)... I will try to find a win. machine where I can get privileged access.

**Comment by krlmlr** [comment]
Can you use the binary package from https://ci.appveyor.com/project/yihui/tikzDevice (click "Artifacts" there)? Alternatively, you can ways use `devtools::build_win()` to check and build a source package on Windows, but you have to change the maintainer's e-mail address in `DESCRIPTION`.

**Comment by pank** [comment]
A couple of observations,

- face in `TeXmetrics` is an integer rather than an normal numeric.  The type should be normalized in the call.
- when you call `getLatexStrWidth` `packages` is typically a list of entries.  However, by the time it's called from tikzDevice, it's been concanated by `\n` into a single string , it seems.  If possible it should be normalized, though this may be nontrivial (e.g. if there's `%` characters).

In general, I think it might be good to allow for an optional more flexible searching to find a string that is "close to" the requested one.  This is probably hard, since you could have TeX commands.  None the less, in the simple case "string", it's probably better to find the sum of width of `[s t r i n g]` than failing, if a latex compiler is not available.

To illustrate. here's my quick script to build a tikzDevice dictionary.  It's failing because more newlines was added to `tikzLatexPackages`.  This is nonsense from a LaTeX perspective.

```
library(tikzDevice)
options(tikzMetricsDictionary=file.path(getwd(), '.tikzMetricsDictionary'), 
        tikzDocumentDeclaration="\\documentclass[DIV=11,headings=big]{scrartcl}", 
        tikzDefaultEngine = "pdftex",
        tikzLatexPackages = c("\\usepackage{tikz}\n",
                              "\\usepackage[active, tightpage, psfixbb]{preview}\n",
                              "\\PreviewEnvironment{pgfpicture}\n",
                              "\\usepackage{libertine}\n",
                              "\\setlength\\PreviewBorder{0pt}\n"))

ligatures <- c("fi", "fj", "fl", "ff", "ct", "st", "ffi", "ffj", "ffl", "fh")
symbols <- c(letters, LETTERS, ligatures, toupper(ligatures), 0:9)
prefixes <- c("", "\\itshape ", "\\bfseries ")
postfixes <- c("", "\\,")
sym <- expand.grid(prefixes, symbols, postfixes, stringsAsFactors = FALSE)
sym <- apply(sym, 1, paste, collapse="")

cexs <- seq(.1, 1, .1)
faces <- as.integer(1:4)
args <- expand.grid(sym, cexs, faces, stringsAsFactors = FALSE)

tmp <- mapply(getLatexStrWidth, texString=args[, 1], cex=args[, 2], face=args[, 3])
```

**Comment by pank** [comment]
Re normalizing input to the database, perhaps something like the following could be used:

```
From 3c9144ca38540110dcc8227fdeeaae1b853abb23 Mon Sep 17 00:00:00 2001
From: Rasmus <rasmus@gmx.us>
Date: Thu, 24 Sep 2015 19:36:06 +0200
Subject: [PATCH] Add some normalization to keys stored in in cache

Normalization matters since the key is sha1 and changes depending on
whether numbers are integers or floats.
---
 R/cacheMetrics.R | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)

diff --git a/R/cacheMetrics.R b/R/cacheMetrics.R
index 8dc6cf4..114cab0 100644
--- a/R/cacheMetrics.R
+++ b/R/cacheMetrics.R
@@ -16,6 +16,7 @@ function( key, verbose )
 {
   # Ensure the dictionary is available.
   checkDictionaryStatus(verbose = verbose)
+  key <- normalizeMetricsKey(key)
 
   # Check for the string.
   haveMetrics <- evalWithoutInterrupts(dbExists(.tikzInternal[['dictionary']], sha1(key)))
@@ -33,6 +34,22 @@ function( key, verbose )
   }
 }
 
+# The sha1 is quite sensitive so it best if the key is normalized
+# before looking it up.  A key is typically requested in the form of
+# char-type (getLatexCharMetrics) or a string-type (getLatexStrWidth).
+normalizeMetricsKey <- function(key){
+    removeChars <- "[\n% \t]"
+    if ((is.list(key)) & key$type %in% c("char", "string")){
+        key <- within(key,{
+            scale <- as.numeric(scale)
+            face <- as.integer(face)
+                documentDeclaration <- gsub(removeChars, "", documentDeclaration)
+            packages <- gsub(removeChars, "", paste0(packages, collapse = ""))
+        })
+    }
+    key
+}
+
 
 # This function enters values into the metrics dictionary. The metrics are
 # stored under a key which is a SHA1 hash created from the object they are
-- 
2.5.3
```

**Comment by krlmlr** [comment]
How about the following non-tech solution: Ask your client if he's willing to settle for slightly lower quality plots (using, say, the `pdf()` device), or if he'll support the installation of one additional piece of software. If you can install `tikzDevice`, I guess it might be possible also to use a [portable version of MikTeX](http://miktex.org/portable)?

**Comment by pank** [comment]
Hi,

Kirill Müller <notifications@github.com> writes:

> How about the following non-tech solution: Ask your client if he's
> willing to settle for slightly lower quality plots (using, say, the
> `pdf()` device), or if he'll support the installation of one
> additional piece of software. If you can install `tikzDevice`, I guess
> it might be possible also to use a [portable version of
> MikTeX](http://miktex.org/portable)?

Indeed it proves much to unpredictable.  I solved the issue with
`showtext` and the correct font plus tweaked R plotting parameters.

Feel free to close unless you'd want to work more on this (I can also
provide patches, if desirable).

Thanks,
Rasmus

PS: There's no client, just confidential data.

-- 
Bang bang

**Comment by krlmlr** [comment]
Thanks for your feedback. I prefer to keep things simple here.
