### ISSUE TITLE
Using simple r-text-output without graphic?

### ISSUE THREAD

**Issue by buhtz** [yihui/tikzDevice#127]
Is there a way to do something like this?

```python
  #!/usr/bin/R -f

  # load the library
  library(tikzDevice)

  # stem-and-leaf plot
  tikz('stem.tex')
  stem(sample(1:30, 20))

  dev.off()
```

`stem()` simply produce text-output. How can I integrate that in my tex-file with tikzDevice?

**Comment by krlmlr** [comment]
How does this plot look like when you use, say, the `png()` device, and how does it differ from the tikzDevice output?

**Comment by buhtz** [comment]
You mean this?

```R
  png('stem.png')
  stem(sample(1:30, 20))
  dev.off()
```
The output is
```
> dev.off()
null device 
          1 
```
No png-file is created.

**Comment by krlmlr** [comment]
If no PNG file is created, I assume the chances are low that tikzDevice will be able to create a .tex file. Does stem() output to the terminal? What does that output look like?

**Comment by buhtz** [comment]
On 2015-11-19 11:38 Kirill Müller <notifications@github.com> wrote:
> Does stem() output to
> the terminal? What does that output look like?

Simple and usual stem() output on the console looks fine.
And I want to integrate that in my tex-document.
-- 
GnuPGP-Key ID 0751A8EC

**Comment by krlmlr** [comment]
I don't think tikzDevice is the right place to handle this. If you want to insert plain command output into your document, simply write the output to a file, and then use `\input{}` to include the contents in your document. (Relevant: http://tex.stackexchange.com/q/85200/8057)

knitr + rmarkdown might also be an option:

```
---
output: pdf_document
---

\begin{verbatim}
```{r, results='asis', echo=FALSE}
stem(sample(1:30, 20))
```
\end{verbatim}
 ```

**Comment by yihui** [comment]
I think this will be more portable (in case you need other output formats):

    ---
    output: pdf_document
    ---
    
    ```{r, comment='', echo=FALSE}
    stem(sample(1:30, 20))
    ```
