### ISSUE TITLE
Require R 3.2.0

### ISSUE THREAD

**Issue by krlmlr** [yihui/tikzDevice#136]
...or remove `CDDDR()`. Uwe Ligges wrote:

> Unfortunately, this does not install under R-oldrelease (R-3.1.3):

> https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/tikzDevice-00install.html

> Please either fix or declare

> Depends: R (>= 3.2.0)

> in your DESCRIPTION (if and only if you only change the latter, a same version update is fine).

**Comment by yihui** [comment]
I'm fine with `R (>= 3.2.0)` if you cannot remove `CDDDR()`.
