### ISSUE TITLE
Add an option to togge verbosity

### ISSUE THREAD

**Issue by mllg** [yihui/tikzDevice#137]
Using neovim and the nvim R plugin (<https://github.com/jalvesaq/Nvim-R>), knitr and rmarkdown are always executed in an interactive session. Thus, the output to PDF is flooded with messages like "using tikz dictionary" etc.

An option to turn this of (instead of asking `interactive()`) would be helpful.

**Comment by krlmlr** [comment]
Makes sense: Create an option, populate it in onLoad with the value of interactive(). Would you like to contribute a PR?

**Comment by yihui** [comment]
I just set `verbose = FALSE` in knitr. If you are unable to install the development version of knitr, you can also set the chunk option `dev.args = list(tikz = list(verbose = FALSE))`.

**Comment by mllg** [comment]
Thanks!
