### ISSUE TITLE
Code from manual not copypastable

### ISSUE THREAD

**Issue by Lenchik** [yihui/tikzDevice#139]
Because of all `'` converted to `’`. Probably because of some default tex ligatures settings that change that symbols.

**Comment by krlmlr** [comment]
Could you please be a bit more specific? Which manual? Which code example have you tested?

**Comment by Lenchik** [comment]
To reproduce:
https://cran.rstudio.com/web/packages/tikzDevice/vignettes/tikzDevice.pdf

Introduction (page 4 numbered as 1). Copy paste of second block of code (same copying result in Adobe reader and STDU Viewer):
```r
tikz(’tikz-example.tex’,
width = 3.25, height = 3.25)
plot(1, 1, main = ’Hello \\TeX !’)
dev.off()
```
Result of pasting it in R from RStudio on russian Windows:
```r
> library(tikzDevice)
> tikz(’tikz-example.tex’,
Error: unexpected input in "tikz(’"
>       width = 3.25, height = 3.25)
Error: unexpected ',' in "      width = 3.25,"
> plot(1, 1, main = ’Hello \\TeX !’)
Error: unexpected input in "plot(1, 1, main = ’"
> dev.off()
Error in dev.off() : не могу отключить устройство 1 (null-устройство)
```
Session info:
```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tikzDevice_0.10

loaded via a namespace (and not attached):
[1] tools_3.2.3  filehash_2.3 grid_3.2.3  
```

**Comment by Lenchik** [comment]
May be http://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html#tex will be helpful ([upquote package](http://www.ctan.org/pkg/upquote)).

**Comment by krlmlr** [comment]
Thanks for reporting, should be fixed now in the dev version.
