### ISSUE TITLE
glossary with tikzDevice

### ISSUE THREAD

**Issue by amit2011** [yihui/tikzDevice#144]
Hi, I am using tikzDevice to run my R-scripts within latex.

This is my code -- 

```
\documentclass{article}
\usepackage[acronym]{glossaries}
\usepackage{tiki} 


\makeglossaries

\newacronym{gcd}{GCD}{Greatest Common Divisor}

\newacronym{lcm}{LCM}{Least Common Multiple}

\begin{document}


    Given a set of numbers, there are elementary methods to compute 
    its \acrlong{gcd}, which is abbreviated \acrshort{gcd}. This 
    process is similar to that used for the \acrfull{lcm}.


    \begin{figure}[!ht]
    \centering
    \input{rtikzFile}
    \end{figure}

\end{document}
```

where rtikzFile is created using R as follows -- 

```
library(tikzDevice)
tikz("rtikzFile.tex" )
options( tikzLatexPackages = c( getOption( "tikzLatexPackages" ), "\\usepackage[acronym]{glossaries}"))
plot(1,1,xlab="XXX")
dev.off()
```

`

Now, I would like to use **`\gls{lcm}`** instead of **XXX** as x-label. I have tried using `\\gls\\{lcm\\}` and also `\\gls{lcm}`. Everything just return errors, something like --

```
File: pgfcorepathusage.code.tex 2013/12/13  (rss-revision 1.23)
\Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for the following string
or character:

    \gls\{lcm\}
```

**Comment by krlmlr** [comment]
Doesn't the glossary require two LaTeX compilation passes? Unless you manage to link the preamble to a precompiled glossary file, the measurement will be off anyway.

The development version will show you the location of the generated .tex and .log files, I've attached them for your convenience.

[tikzStringWidthCalc.log.txt](https://github.com/yihui/tikzDevice/files/326625/tikzStringWidthCalc.log.txt)
[tikzStringWidthCalc.tex.txt](https://github.com/yihui/tikzDevice/files/326626/tikzStringWidthCalc.tex.txt)

**Comment by amit2011** [comment]
Right, even it would need `\makeglossaries`in the preamble. Is there a way to pass precompiled glossary file to the r-script ?

**Comment by krlmlr** [comment]
Honestly, I have no idea. I'd probably use a simpler approach, e.g., use the raw text in the plots and later do a text substitution in the generated .tex file.

**Comment by amit2011** [comment]
ok. I already tried to edit it in generated .tex file, as expected, that works perfectly. Thanks for pointer to the problem.
