### ISSUE TITLE
Huge files with large datasets

### ISSUE THREAD

**Issue by menecken** [yihui/tikzDevice#146]
I found the bug when I wanted to draw a histogram along with a manually drawn `geom_rect` using

```
`library(tikzDevice)
library(ggplot2)
library(dplyr)

  debugData <- c(0, rep(1,500), 45000)
  p <- ggplot() +
    geom_histogram() +
    aes(debugData) +
    geom_rect(xmin = 40000, xmax = 41000, ymin = 0, ymax = 50, fill= "#595959")

  texfilePath <- paste0( "output/debug.tex")
  tikz(texfilePath, width=4, height=2)
  print(p)
  #Close the device
  dev.off()
```

This code results already in a 42kb large .TEX file.

Output looks like

![bughunt](https://cloud.githubusercontent.com/assets/9052196/17582820/dde46998-5fad-11e6-8aec-efd04c4fa9ec.PNG)

When changing `rep(1,500)` to `rep(1,100000)` the file is 6649kb large which causes the TeX compiler to throw an obvious error: `TeX capacity exceeded, sorry [main memory size=3000000]. ...6.78, 35.61) rectangle (251.32, 35.66);`

The reason are many duplicated lines in the outputted TeX:

```
\path[fill=fillColor] (251.87, 35.61) rectangle (258.91, 35.61);

\path[fill=fillColor] (258.91, 35.61) rectangle (265.96, 35.61);

\path[fill=fillColor] (265.96, 35.61) rectangle (273.01, 35.61);
```

This line is repeated 100002 times.

[bughunt.R.txt](https://github.com/yihui/tikzDevice/files/412787/bughunt.R.txt)

**Comment by krlmlr** [comment]
Thanks. Vector graphics consisting of many individual objects tend to lead to huge file sizes, there's nothing we can do about it. Please consider using PNG or simplifying your plot.
