### ISSUE TITLE
unable to use labels = percent_format() in scale

### ISSUE THREAD

**Issue by fzesch** [yihui/tikzDevice#151]
I want to plot with `ggplot` and `percent_format()` from `scales` like

    ggplot(df, aes(Weight.kg)) +
       geom_histogram(aes(y = ..count../(sum(..count..))), binwidth = 0.2,) + 
       scale_y_continuous(labels = percent_format())

But I receive the error

> 
> TeX was unable to calculate metrics for the following string
> or character:
> 
> 	0%
> 
> Common reasons for failure include:
>   * The string contains a character which is special to LaTeX unless
>     escaped properly, such as % or $.
>   * The string makes use of LaTeX commands provided by a package and
>     the tikzDevice was not told to load the package.

Which is of course a perfectly escaped error but nevertheless keeps me from getting my figure.

**Comment by krlmlr** [comment]
Thanks. The `%` leaks into the generated LaTeX code. You need to run `tikz(sanitize = FALSE)` (which prevents you from using LaTeX in your plots) or escape the percent characters yourself (with a custom formatter that wraps `percent_format()`).

**Comment by fzesch** [comment]
Thanks. Just for the sake of completeness: The correct command is `tikz(sanitize = TRUE)` if I want to get the right output. I did not know about this option, thanks for the help!
