### ISSUE TITLE
tikzDevice not working for basic example

### ISSUE THREAD

**Issue by ntguardian** [yihui/tikzDevice#152]
Consider the following example:

```
library(tikzDevice)
tikz("test.tex")
plot(1:10)
dev.off()

```
An error will be produced once the plot is created, with a lot of code but near the end the error appears:

```
("C:\ProgramError in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for the following string
or character:

    m

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

The contents of the LaTeX log of the aborted run have been printed above,
it may contain additional details as to why the metric calculation failed.
In addition: Warning messages:
1: In readLines(texLog) :
  incomplete final line found on 'C:\Users\cgmil\AppData\Local\Temp\Rtmp6FouwP/tikzStringWidthCalc.log'
2: In readLines(texLog) :
  incomplete final line found on 'C:\Users\cgmil\AppData\Local\Temp\Rtmp6FouwP/tikzStringWidthCalc.log'

```

There are other examples from websites and the tikzDevice vignette that are not working; sometimes they point to the string/character "m", sometimes a mysterious number like "36".

All of this is on a machine I bought on Sunday, so my version of all these packages should presumably be the most recent version. What's going on?

I noticed that I do not have this problem on my work computer, where I installed this package today. So here is the session information for the installation with which I'm having the problem.

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tikzDevice_0.10-1

loaded via a namespace (and not attached):
[1] tools_3.3.2  filehash_2.3 grid_3.3.2  
```

**Comment by krlmlr** [comment]
Thanks. The development version now has `tikzTest()` which can help troubleshoot problems. Please open a new issue if the problems persist.

Install the development version via

```r
# install.packages("remotes")
remotes::install_github("yihui/tikzDevice")
```

**Comment by WhiskersReneeWe** [comment]
I have the same issue. Really can't figure it out where it went wrong.

**Comment by dnkent** [comment]
Longtime fan of tikzDevice here, but out of nowhere am having the same problem as above.

**Comment by rstub** [comment]
@WhiskersReneeWe , @dnkent: Please post the output of `tikzTest()`, preferably in a new issue.

**Comment by dnkent** [comment]
Problem solved! 

I installed Tex Live and then followed the advice from [149](https://github.com/daqana/tikzDevice/issues/149) and ran `tinytex::tlmgr_install(c("pgf", "preview", "ms", "graphics", "pdftex-def", "oberdiek", "ec", "xcolor", "fontspec", "xunicode"))
`
