### ISSUE TITLE
Write Errors, cannot open file.

### ISSUE THREAD

**Issue by nhamilton1980** [yihui/tikzDevice#153]
I am getting write errors when using pdftex, 

```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/var/folders/67/ys78wlfd43zc4rzmvbtfthqh0000gn/T//RtmpArEDDV/tikzStringWidthCalc.log': No such file or directory
```
I think it is due to the following:

**Around Line 270, `latexStrWidth.R`**

Should also have:

```
if(!file.exists(texLog)) file.create(texLog)
```

Same error does not happen when using xetex

In a local version I made the following changes, which made the error go away once the package was rebuilt and reloaded:

```
### LINE 266, latexStrWidth.R
texDir  <- tempdir()
texLog  <- file.path(texDir, 'tikzStringWidthCalc.log')
texFile <- file.path(texDir, 'tikzStringWidthCalc.tex')
fun     <- function(x){ if (!file.exists(x)) file.create(x); normalizePath(x,'/') }
texLog  <- fun(texLog)
texFile <- fun(texFile)

# Open the TeX file for writing.
texIn <- file(texFile, 'w')
### END MODIFICATION
```

**Comment by yihui** [comment]
Could you submit a pull request? Thanks!

**Comment by krlmlr** [comment]
Thanks, I don't think creating the .tex and .log files is necessary. Please open a new issue if the problem persists.
