### ISSUE TITLE
Redact creation date from file

### ISSUE THREAD

**Issue by ThomDietrich** [yihui/tikzDevice#174]
Hey guys,
sorry if I didn't find the existing setting for this request.

Every file generated with tikzDevice starts with the following:

```tex
% Created by tikzDevice version 0.10.1 on 2018-02-18 18:55:42
% !TEX encoding = UTF-8 Unicode
\begin{tikzpicture}[x=1pt,y=1pt]
...
```

... or similar. Because I'm tracking my project with git, I want to see changes to a file only if real content changed. Right now every time a file is regenerated, the timestamp changes.

Is an option available to suppress the timestamp insertion during generation?

**Comment by krlmlr** [comment]
Running `tikz(..., timestamp = FALSE)` will omit the timestamp.

**Comment by ThomDietrich** [comment]
And this is in fact documented. Thank you very much!
