### ISSUE TITLE
Weird issue when setting OutDec option

### ISSUE THREAD

**Issue by krlmlr** [yihui/tikzDevice#57]
See hadley/ggplot2#760

**Comment by krlmlr** [comment]
Thanks for looking into this. A CRAN release is overdue, I was waiting for the update of filehash, but it looks like it'll be some time. (I asked Roger Peng several times, even submitted a pull request to fix CRAN errors -- to no avail.)

Is there a better alternative to filehash?

**Comment by yihui** [comment]
Let me ping him in a minute.

**Comment by yihui** [comment]
The new version of filehash is on CRAN now.
