### ISSUE TITLE
Test with R versions older than 3.1.0

### ISSUE THREAD

**Issue by krlmlr** [yihui/tikzDevice#96]
Problem: Needs earlier version of `testthat` and perhaps other packages. The `cran/*` GitHub repos have tags of the form `R-x.y.z` which can be used to achieve this, until there's an automated solution like MRAN (which doesn't seem to have snapshots before August 2014).

**Comment by yihui** [comment]
Fortunately we do not have hundreds of reverse dependencies on CRAN, so you should just enjoy the freedom, and bravely require R > 3.1.0 :)

**Comment by krlmlr** [comment]
This requirement would be somewhat artificial and could prevent users from using it. How many users who are working with an older R version would manually dig into CRAN's archives to look for a matching version of a package? The worst that can happen to us is a bug report, and I haven't seen any so far.

If only one could automagically install a package that matches the current R version...

**Comment by krlmlr** [comment]
Closing this -- let checkpoint and packrat take care of that :-)
